# Generated by Django 4.2.3 on 2023-10-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=50)),
                ("variant", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("price_after_offer", models.IntegerField(default=0)),
                ("stock", models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
