# Generated by Django 4.2.3 on 2023-10-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=50, unique=True)),
                ("uemail", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50, null=True)),
                ("upassword", models.CharField(max_length=50)),
                ("uactive", models.BooleanField(default=True)),
                (
                    "uimage",
                    models.ImageField(blank=True, null=True, upload_to="imagestore/"),
                ),
                ("uotp", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=12)),
                ("housename", models.CharField(max_length=50)),
                ("locality", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("KARNATAKA", "KARNATAKA"),
                            ("KERALA", "KERALA"),
                            ("TAMIL NADU", "TAMIL NADU"),
                            ("GOA", "GOA"),
                            ("GUJARAT", "GUJARAT"),
                        ],
                        default="KERALA",
                        max_length=50,
                    ),
                ),
                ("selected", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.userdetail",
                    ),
                ),
            ],
        ),
    ]
